package com.example.hellospring.dao;

import com.example.hellospring.model.SmsCouponProductRelation;
import com.example.hellospring.model.SmsCouponProductRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsCouponProductRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    long countByExample(SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int deleteByExample(SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int insert(SmsCouponProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int insertSelective(SmsCouponProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    List<SmsCouponProductRelation> selectByExample(SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    SmsCouponProductRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") SmsCouponProductRelation record, @Param("example") SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int updateByExample(@Param("record") SmsCouponProductRelation record, @Param("example") SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int updateByPrimaryKeySelective(SmsCouponProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Mon Mar 09 23:30:12 CST 2020
     */
    int updateByPrimaryKey(SmsCouponProductRelation record);
}